import pickle



states={ { 0  :  {'state' : 'New York',
                  'capital' : 'Albany'}
         },

         { 1  :  {'state' : 'Alabama',
                  'capital' : 'Montgomery'},
         },
         { 2  :  {'state' : 'Alaska',
                  'capital' : 'Juneau'},
         },
         { 3  :  {'state' : 'Arizona',
                  'capital' : 'Phoenix'},
         },
         { 4  :  {'state' : 'Arkansas',
                  'capital' : 'Little Rock'},
         },
         { 5  :  {'state' : 'California',
                  'capital' : 'Sacramento'},
         },
         { 6  :  {'state' : 'Colorado',
                  'capital' : 'Denver'},
         },
         { 7  :  {'state' : 'Connecticut',
                  'capital' : 'Hartford'},
         },
         { 8  :  {'state' : 'Delaware',
                  'capital' : 'Dover'},
         },
         { 9 :  {'state' : 'Florida',
                  'capital' : 'Tallahassee'},
         },
         { 10 :  {'state' : 'Georgia',
                  'capital' : 'Atlanta'},
         },
         { 11 :  {'state' : 'Hawaii',
                  'capital' : 'Honolulu'},
         },
         { 12 :  {'state' : 'Idaho',
                  'capital' : 'Boise'},
         },
         { 13 :  {'state' : 'Illinois',
                  'capital' : 'Springfield'},
         },
         { 14 :  {'state' : 'Indiana',
                  'capital' : 'Indianapolis'},
         },
         { 15 :  {'state' : 'Iowa',
                  'capital' : 'Des Moines'},
         },
         { 16 :  {'state' : 'Kansas',
                  'capital' : 'Topeka'},
         },
         { 17 :  {'state' : 'Kentucky',
                  'capital' : 'Frankfort'},
         },
         { 18 :  {'state' : 'Louisiana',
                  'capital' : 'Baton Rouge'},
         },
         { 19 :  {'state' : 'Maine',
                  'capital' : 'Augusta'},
         },
         { 20 :  {'state' : 'Maryland',
                  'capital' : 'Annapolis'},
         },
         { 21 :  {'state' : 'Massachusets',
                  'capital' : 'Boston'},
         },
         { 22 :  {'state' : 'Michigan',
                  'capital' : 'Lansing'},
         },
         { 23 :  {'state' : 'Minnesota',
                  'capital' : 'Saint Paul'},
         },
         { 24 :  {'state' : 'Mississippi',
                  'capital' : 'Jackson'},
         },
         { 25 :  {'state' : 'Missouri',
                  'capital' : 'Jefferson City'},
         },
         { 26 :  {'state' : 'Montana',
                  'capital' : 'Helena'},
         },
         { 27 :  {'state' : 'Nebraska',
                  'capital' : 'Lincoln'},
         },
         { 28 :  {'state' : 'Nevada',
                  'capital' : 'Carson City'},
         },
         { 29 :  {'state' : 'New Hampshire',
                  'capital' : 'Concord'},
         },
         { 30 :  {'state' : 'New Jersey',
                  'capital' : 'Trenton'},
         },
         { 31 :  {'state' : 'New Mexico',
                  'capital' : 'Santa Fe'},
         },
         { 32 :  {'state' : 'North Carolina',
                  'capital' : 'Raleigh'},
         },
         { 33 :  {'state' : 'North Dakota',
                  'capital' : 'Bismarck'},
         },
         { 34 :  {'state' : 'Ohio',
                  'capital' : 'Columbus'},
         },
         { 35 :  {'state' : 'Oklahoma',
                  'capital' : 'Oklahoma City'},
         },
         { 36 :  {'state' : 'Oregon',
                  'capital' : 'Salem'},
         },
         { 37 :  {'state' : 'Pennsylvania',
                  'capital' : 'Harrisburg'},
         },
         { 38 :  {'state' : 'Rhode Island',
                  'capital' : 'Providence'},
         },
         { 39 :  {'state' : 'South Carolina',
                  'capital' : 'Columbia'},
         },
         { 40 :  {'state' : 'South Dakota',
                  'capital' : 'Pierre'},
         },
         { 41 :  {'state' : 'Tennessee',
                  'capital' : 'Nashville'},
         },
         { 42 :  {'state' : 'Texas',
                  'capital' : 'Austin'},
         },
         { 43 :  {'state' : 'Utah',
                  'capital' : 'Salt Lake City'},
         },
         { 44 :  {'state' : 'Vermont',
                  'capital' : 'Montpelier'},
         },
         { 45 :  {'state' : 'Virginia',
                  'capital' : 'Richmond'},
         },
         { 46 :  {'state' : 'Washington',
                  'capital' : 'Olympia'},
         },
         { 47 :  {'state' : 'West Virginia',
                  'capital' : 'Charleston'},
         },
         { 48 :  {'state' : 'Wisconsin',
                  'capital' : 'Madison'},
         },
         { 49 :  {'state' : 'Wyoming',
                  'capital' : 'Cheyenne'}
         }
}

try:
    SCDict = open('SandCO', 'w')
    pickle.dump(states, SCDict)
    SCDict.close()

except:
    print('Shit has gone downhill, this dict is acting like a dick...')